server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://rttunsodbmeewt:1c97c2242b8b09dfc9887db9f4dfea97b81197e967d42a34fc24453a2427ceb6@ec2-34-192-210-139.compute-1.amazonaws.com:5432/dag9ju8jj0oaf1
    username: rttunsodbmeewt
    password: 1c97c2242b8b09dfc9887db9f4dfea97b81197e967d42a34fc24453a2427ceb6
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
#          facebook:
#            client-id:
#            client-secret:
#            scope:
#              - email
#              - public_profile
          google:
            client-id: 517447956930-ks6o0nu247mmb6pe9ag6gl2533443hvf.apps.googleusercontent.com
            client-secret: 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
#            scope:
#              - email
#              - profile
  application:
    name: USER-SERVICE

